name: GitHub Actions Pull
on: [pull]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
      - uses: actions/setup-go@v2
      with:
        go-version: "1.16.0"
      - name: check version
        run : go version